theme: jekyll-theme-minimal
title: ".NET Foundation Elections"
description: ""

collections:
  campaign-2019:
    output: true

# Google Analytics
google_analytics: UA-57261022-1

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap